name: Deploy Article to Production

on: [push]

env:
  CI: true
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DX_HEADER: ${{ secrets.DX_HEADER }}
  IMPORT_URL: ${{ secrets.IMPORT_URL }}
  IMPORT_URL_STAGING: ${{ secrets.IMPORT_URL_STAGING }}
  KB_VALIDATION_URL: ${{ secrets.KB_VALIDATION_URL }}
  X_DX_AUTH_HEADER: ${{ secrets.X_DX_AUTH_HEADER }}

jobs:
  deploy-to-production:
    if: github.ref == 'master'
    needs: check-article
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Deploy to developerexperience.io
        run: 'curl -f -XPOST -H "$DX_HEADER" $IMPORT_URL'
